/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Imu.h
  Source: /home/meshin/dev/quadruped/xterra/quadruped_locomotion/src/communication/msgs/idl/Imu.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_IMU_H
#define DDSC_IMU_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct msgs_Imu
{
  float q[4];
  float gyro[3];
  float accel[3];
  float rpy[3];
  uint8_t tmp;
} msgs_Imu;

extern const dds_topic_descriptor_t msgs_Imu_desc;

#define msgs_Imu__alloc() \
((msgs_Imu*) dds_alloc (sizeof (msgs_Imu)));

#define msgs_Imu_free(d,o) \
dds_sample_free ((d), &msgs_Imu_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_IMU_H */
