/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: LowState.h
  Source: /home/meshin/dev/quadruped/xterra/quadruped_locomotion/src/communication/msgs/idl/LowState.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_LOWSTATE_H
#define DDSC_LOWSTATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct msgs_LowState
{
  float q[12];
  float dq[12];
  float ddq[12];
  float tau_est[12];
  float tmp[12];
  float contact[4];
  float quat[4];
  float gyro[3];
  float accel[3];
  float rpy[3];
  uint8_t imu_tmp;
  float voltage;
  float current;
} msgs_LowState;

extern const dds_topic_descriptor_t msgs_LowState_desc;

#define msgs_LowState__alloc() \
((msgs_LowState*) dds_alloc (sizeof (msgs_LowState)));

#define msgs_LowState_free(d,o) \
dds_sample_free ((d), &msgs_LowState_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LOWSTATE_H */
