controller_joint_names: ['', 'RF_HAA_JOINT', 'RF_HFE_THIGH', 'RF_KFE_JOINT', 'LF_HAA_JOINT', 'LF_HFE_JOINT', 'LF_KFE_JOINT', 'LH_HAA_JOINT', 'LH_HFE_JOINT', 'LH_KFE_JOINT', 'RH_HAA_JOINT', 'RH_HFE_JOINT', 'RH_KFE_JOINT', ]
