"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: Go2Py.unitree_go.msg.dds_
  IDL file: Go2pyLowCmd.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import Go2Py.unitree_go

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Go2pyLowCmd_(idl.IdlStruct, typename="unitree_go.msg.dds_.Go2pyLowCmd_"):
    q: types.array[types.float32, 12]
    dq: types.array[types.float32, 12]
    kp: types.array[types.float32, 12]
    kd: types.array[types.float32, 12]
    tau: types.array[types.float32, 12]


