"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: msgs
  IDL file: LowState.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowState(idl.IdlStruct, typename="msgs.LowState"):
    q: types.array[types.float32, 12]
    dq: types.array[types.float32, 12]
    ddq: types.array[types.float32, 12]
    tau_est: types.array[types.float32, 12]
    tmp: types.array[types.float32, 12]
    contact: types.array[types.float32, 4]
    quat: types.array[types.float32, 4]
    gyro: types.array[types.float32, 3]
    accel: types.array[types.float32, 3]
    rpy: types.array[types.float32, 3]
    imu_tmp: types.uint8
    voltage: types.float32
    current: types.float32


