environment:
  simulation_dt: 0.01
  rendering_dt: 0.02
  prim_path: "/World/Env"
  buildin: true
  usd_path: "/Isaac/Environments/Grid/default_environment.usd" # /Isaac/Environments/Simple_Warehouse/full_warehouse.usd
  synchronous_mode: false # if true, the simulator will wait for the control commands from the LCM channel for 0.1 seconds

robots:
  - prim_path: "/World/Env/GO2"
    usd_path: ""
    name: "go2"
    usd_file: "assets/usd/go2.usd"
    position: [0.0, 0.0, 0.8]
    orientation: [0.0, 0.0, 0.0, 1.0]

cameras:
  - prim_path: "/World/Env/GO2/imu_link"
    name: "test_camera"
    type: ["rgb", "distance_to_camera"]
    resolution: [1280, 720]
    interstice_parameters:
      K: [1000, 1000, 500, 500]
      D: [0.1, 0.2, 0.1, 0.0]
    translation: [0.0, 0.0, 0.0] # x, y, z
    orientation: [0.0, 0.0, 0.0, 1.0] # qx, qy, qz, qw

  